name: Deploy Infra
on: [workflow_dispatch, push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with: { client-id: ${{ secrets.AZ_CLIENT_ID }}, tenant-id: ${{ secrets.AZ_TENANT_ID }}, subscription-id: ${{ secrets.AZ_SUB }} }
      - uses: hashicorp/setup-terraform@v3
      - run: |
          cd infra
          terraform init
          terraform apply -auto-approve -var="prefix=${{ vars.PREFIX }}" -var="location=eastus"
      - id: tfout
        run: |
          cd infra
          echo "STORAGE_URL=$(terraform output -raw storage_url)" >> $GITHUB_OUTPUT
          echo "SAS=$(terraform output -raw sas_token)" >> $GITHUB_OUTPUT
          echo "BATCH=$(terraform output -raw batch_name)" >> $GITHUB_OUTPUT
      - name: Upload app + sample inputs
        run: |
          pipx install azure-cli
          az storage blob upload-batch --destination packages --source app --account-endpoint "${{ steps.tfout.outputs.STORAGE_URL }}" --sas-token "${{ steps.tfout.outputs.SAS }}"
          # put example images into input/ (commit some small PNGs in repo's samples/ or add your own)
          az storage blob upload-batch --destination input --source samples --account-endpoint "${{ steps.tfout.outputs.STORAGE_URL }}" --sas-token "${{ steps.tfout.outputs.SAS }}"
