name: Destroy Infra
on: [workflow_dispatch]
jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with: { client-id: ${{ secrets.AZ_CLIENT_ID }}, tenant-id: ${{ secrets.AZ_TENANT_ID }}, subscription-id: ${{ secrets.AZ_SUB }} }
      - uses: hashicorp/setup-terraform@v3
      - run: cd infra && terraform destroy -auto-approve
